import type { Metadata } from "next"
import { Lalezar } from "next/font/google"

import "./globals.css"

const lalezar = Lalezar({
  variable: "--font-lalezar",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lalezar.variable} antialiased`}>{children}</body>
    </html>
  )
}
